---

# Here are variables related to the Tomcat installation

http_port: $ANSIBLE_VAULT;1.1;AES256
           65616466316336643333633935613834353636653837663434376437663830393363363237393361
           3761323537633363336463616232343561323730633932310a653834346434346334393064653433
           64343537636365396535656463343534363865623330626333643864323364366436313537666632
           3136383035663965630a303035353731316132663339333438343730386135386135313965316665
           64303239363330393163303333353639633335383165616161613762383338343035
https_port: 8443
tomcat_user: tomcat
tomcat_group: tomcat
jdk_version: java-1.7.0-openjdk


admin_username: admin
admin_password: adminsecret
